### ISSUE TITLE
Useless error message if wrong file path is given

### ISSUE THREAD

**Issue by silentsnooc** [T0ha/ezodf#19]
```
Traceback (most recent call last):
  File "/home/yyyyyyy/loop_list_test.py", line 9, in <module>
    adapted_ods = ezodf.opendoc(adapted)
  File "/usr/local/lib/python2.7/dist-packages/ezodf/document.py", line 54, in opendoc
    mime_type = __detect_mime_type(fm)
  File "/usr/local/lib/python2.7/dist-packages/ezodf/document.py", line 69, in __detect_mime_type
    mime_type = MIMETYPES[ext]
KeyError: '.ods'

```

**Comment by franciscod** [comment]
Got bitten by this error. I had restructured some directories and didn't notice the path wasn't right. Thanks for filing this bug!
